hourglass/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :clients
  resources :events

  root 'events#new'

end

hourglass/app/models/client.rb
class Client < ActiveRecord::Base
	belongs_to :user
	has_many :events
end

hourglass/app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user
	belongs_to :client
end

hourglass/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events
end

hourglass/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  layout :layout_by_resource

  protected

  def layout_by_resource
    if user_signed_in?
      "dashboard"
    else
      "application"
    end
  end
end

hourglass/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name)
    end
end

hourglass/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name)
    end
end

hourglass/app/helpers/application_helper.rb
module ApplicationHelper
end

hourglass/app/helpers/clients_helper.rb
module ClientsHelper
end

hourglass/app/helpers/events_helper.rb
module EventsHelper
end

hourglass/app/views/clients/_form.html.haml
= form_for(@client) do |f|
  - if @client.errors.any?
    #error_explanation
      %h2
        = pluralize(@client.errors.count, "error")
        prohibited this client from being saved:
      %ul
        - @client.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .actions
    = f.submit

hourglass/app/views/clients/edit.html.haml
%h1 Editing Client
= render 'form'
= link_to 'Show', @client
|
= link_to 'Back', clients_path

hourglass/app/views/clients/index.html.haml
%p#notice= notice
%h1 Listing Clients
%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"}
  %tbody
    - @clients.each do |client|
      %tr
        %td= client.name
        %td= link_to 'Show', client
        %td= link_to 'Edit', edit_client_path(client)
        %td= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Client', new_client_path

hourglass/app/views/clients/new.html.haml
%h1 New Client
= render 'form'
= link_to 'Back', clients_path

hourglass/app/views/clients/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @client.name
= link_to 'Edit', edit_client_path(@client)
|
= link_to 'Back', clients_path

hourglass/app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  - if @event.errors.any?
    #error_explanation
      %h2
        = pluralize(@event.errors.count, "error")
        prohibited this event from being saved:
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .field
    = f.input_field :name
  .actions
    = f.submit

hourglass/app/views/events/edit.html.haml
%h1 Editing Event
= render 'form'
= link_to 'Show', @event
|
= link_to 'Back', events_path

hourglass/app/views/events/index.html.haml
%p#notice= notice
%h1 Listing Events
%table
  %thead
    %tr
      %th Name
      %th{colspan: "3"}
  %tbody
    - @events.each do |event|
      %tr
        %td= event.name
        %td= link_to 'Show', event
        %td= link_to 'Edit', edit_event_path(event)
        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Event', new_event_path

hourglass/app/views/events/new.html.haml
%h1 New Event
= render 'form'
= link_to 'Back', events_path

hourglass/app/views/events/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @event.name
= link_to 'Edit', edit_event_path(@event)
|
= link_to 'Back', events_path

hourglass/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Hourglass
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

hourglass/app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/