malibux/config/routes.rb
Rails.application.routes.draw do
  resources :rolls do
    get :init_roll, on: :member, format: false 
    get :roll_update, on: :member, format: false
  end

  resources :tasks 
  
  resources :clients

  resources :servers do
  end

  root 'rolls#index'

end

malibux/app/models/server.rb
class Server < ActiveRecord::Base
	has_many :tasks
	has_many :rolls
	belongs_to :client
end

malibux/app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy]

  # GET /servers
  # GET /servers.json
  def index
    @servers = Server.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = Server.new
  end

  # GET /servers/1/edit
  def edit
  end

  def roll_call
    render 'server_roll_call'
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = Server.new(server_params)

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = Server.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params[:server].permit(:name)
    end
end

malibux/app/helpers/servers_helper.rb
module ServersHelper
end

malibux/app/views/servers/_form.html.haml
= simple_form_for(@server) do |f|
  - if @server.errors.any?
    #error_explanation
      %h2
        = pluralize(@server.errors.count, "error")
        prohibited this server from being saved:
      %ul
        - @server.errors.full_messages.each do |message|
          %li= message
  .actions
    = f.input :name
    = f.submit

malibux/app/views/servers/edit.html.haml
%h1 Editing Server
= render 'form'
= link_to 'Show', @server
|
= link_to 'Back', servers_path

malibux/app/views/servers/index.html.haml
%p#notice= notice
%h1 Listing Servers
%table
  %thead
    %tr
      %th{colspan: "3"}
  %tbody
    - @servers.each do |server|
      %tr
        %td server.name
        %td= link_to 'Show', server
        %td= link_to 'Edit', edit_server_path(server)
        %td= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Server', new_server_path

malibux/app/views/servers/new.html.haml
%h1 New Server
= render 'form'
= link_to 'Back', servers_path

malibux/app/views/servers/server_roll_call.html.haml
-Server.all.each do |server|
  /= render 'single_form'
  %p server.name
  =link_to "check", server_check_server_path(server)

malibux/app/views/servers/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_server_path(@server)
|
= link_to 'Back', servers_path