malibux/config/routes.rb
Rails.application.routes.draw do
  resources :rolls do
    get :init_roll, on: :member, format: false 
    get :roll_update, on: :member, format: false
  end

  resources :tasks 
  
  resources :clients

  resources :servers do
  end

  root 'rolls#index'

end

malibux/app/models/roll.rb
class Roll < ActiveRecord::Base
	belongs_to :server
end

malibux/app/controllers/rolls_controller.rb
class RollsController < ApplicationController
  before_action :set_roll, only: [:show, :edit, :update, :destroy, :server_check]

  # GET /rolls
  # GET /rolls.json
  def index
    @rolls = Roll.all
  end

  # GET /rolls/1
  # GET /rolls/1.json
  def show
  end

  # GET /rolls/new
  def new
    @roll = Roll.new
  end

  # GET /rolls/1/edit
  def edit
  end

  # POST /rolls
  # POST /rolls.json

  def init_roll
    Server.all.each do |s|
      s.rolls.create(:name=>Time.now)
    end
    redirect_to :back
  end

  def roll_update
    @server = Server.find(params[:id])  
    @server.rolls.create(
    :name=>Time.now)
    redirect_to :back
  end

  def create
    @roll = Roll.new(roll_params)

    respond_to do |format|
      if @roll.save
        #format.html { redirect_to @roll, notice: 'Roll was successfully created.' }
        format.html { redirect_to rolls_url, notice: 'Roll was successfully created.' }
        format.json { render :show, status: :created, location: @roll }
      else
        format.html { render :new }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rolls/1
  # PATCH/PUT /rolls/1.json
  def update
    respond_to do |format|
      if @roll.update(roll_params)
        #format.html { redirect_to @roll, notice: 'Roll was successfully updated.' }
        format.html { redirect_to :back, notice: 'Roll was successfully updated.' }

        format.json { render :show, status: :ok, location: @roll }
      else
        format.html { render :edit }
        format.json { render json: @roll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rolls/1
  # DELETE /rolls/1.json
  def destroy
    @roll.destroy
    respond_to do |format|
      format.html { redirect_to rolls_url, notice: 'Roll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roll
      @roll = Roll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roll_params
      params.require(:roll).permit(:name)
    end
end

malibux/app/helpers/rolls_helper.rb
module RollsHelper
end

malibux/app/views/rolls/_form.html.haml
= simple_form_for(r) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit

malibux/app/views/rolls/_single_form.html.haml
= simple_form_for(Roll.new) do |f|
  = f.error_notification
  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit

malibux/app/views/rolls/edit.html.haml
%h1 Editing Roll
= render 'form'
= link_to 'Show', @roll
|
\#{link_to 'Back', rolls_path}

malibux/app/views/rolls/index.html.haml
%p#notice= notice
=link_to "Initiate Server Check", init_roll_roll_path(1)
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @rolls.each do |r|
      %tr
        %td
        %td
          = render 'form',  r: r
        /%td= roll.name
        /%td= link_to 'Show', roll
        /%td= link_to 'Edit', edit_roll_path(roll)
        /%td= link_to 'Destroy', roll, method: :delete, data: { confirm: 'Are you sure?' }
/  = link_to 'New Roll', new_roll_path

malibux/app/views/rolls/new.html.haml
%h1 New Roll
=link_to "Initiate Server Check", init_roll_roll_path(1)


-Roll.all.each do |r|
  = render 'form',  r: r
  %p 
    =r.server.name
    =r.name



  /=link_to "check", server_check_roll_path(server.id)


/= link_to 'Back', rolls_path

malibux/app/views/rolls/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @roll.name
= link_to 'Edit', edit_roll_path(@roll)
|
\#{link_to 'Back', rolls_path}